apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-backend
  namespace: movie-sentiment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-backend
  template:
    metadata:
      labels:
        app: movie-backend
    spec:
      containers:
        - name: flask-app
          image: kevalpithiya/movie-sentiment-api:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: movie-secrets
            - configMapRef:
                name: movie-config
