apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-frontend
  namespace: movie-sentiment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-frontend
  template:
    metadata:
      labels:
        app: movie-frontend
    spec:
      containers:
        - name: react-app
          image: kevalpithiya/movie-sentiment-frontend:latest
          ports:
            - containerPort: 80
